import * as vscode from 'vscode';
import * as path from 'path';
import * as fs from 'fs';

// ✅ สร้างไฟล์ Dart จาก template
export async function createJourneyExperience(folderUri: vscode.Uri) {
  // 1️⃣ ขอชื่อจากผู้ใช้
  const name = await vscode.window.showInputBox({
    prompt: 'Enter Journey Experience name (e.g. onboarding)',
    placeHolder: 'onboarding',
    validateInput: (v) => v.trim() === '' ? 'Name required' : null
  });
  if (!name) return;

  // 2️⃣ แปลงชื่อให้เป็น snake_case หรืออื่น ๆ ตามต้องการ
  const snake = name.replace(/\s+/g, '_').toLowerCase();

  // 3️⃣ ระบุ path ที่จะสร้าง
  const folderPath = path.join(folderUri.fsPath, snake);
  const filePath = path.join(folderPath, `${snake}_journey_experience.dart`);

  // 4️⃣ สร้างโฟลเดอร์
  fs.mkdirSync(folderPath, { recursive: true });

  // 5️⃣ template เนื้อไฟล์ Dart (แก้ได้ตามใจคุณ)
  const template = `
/// ${name} Journey Experience
/// Auto-generated by VSCode extension

import 'package:flutter/material.dart';

class ${_toClassCase(name)}JourneyExperience extends StatelessWidget {
  const ${_toClassCase(name)}JourneyExperience({super.key});

  @override
  Widget build(BuildContext context) {
    return const Scaffold(
      body: Center(
        child: Text('${name} Journey Experience'),
      ),
    );
  }
}
`;

  // 6️⃣ เขียนไฟล์
  fs.writeFileSync(filePath, template, { encoding: 'utf8' });

  // 7️⃣ เปิดใน editor
  const doc = await vscode.workspace.openTextDocument(filePath);
  vscode.window.showTextDocument(doc);

  vscode.window.showInformationMessage(`Created journey: ${name}`);
}

// 🔹 Helper: แปลงชื่อเป็น PascalCase
function _toClassCase(name: string): string {
  return name
    .split(/[_\s-]+/)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join('');
}